import { format } from 'date-fns';
import { es } from 'date-fns/locale';

/**
 * Shared E2E test data + locale-aware helpers.
 *
 * The ERP is Argentinian (es-AR): UI labels, calendar and time selectors are
 * rendered in Spanish. These helpers compute deterministic values so the
 * tests are NOT coupled to hardcoded texts (anti-fragile automation).
 */

// ── Auth fixtures ─────────────────────────────────────────────────────────

/** Seed admin credentials (packages/db/prisma/seed.ts). */
export const E2E_TEST_EMAIL = process.env['E2E_USER_EMAIL'] ?? 'admin@admin.com';
export const E2E_TEST_PASSWORD =
  process.env['E2E_USER_PASSWORD'] ?? 'admin123';

/** Storage file generated by auth.setup.ts. */
export const AUTH_STORAGE_STATE = 'e2e/.auth/user.json';

// ── Unique data generation (avoids Prisma P2002 unique constraint) ───────

/**
 * Unique suffix per test run: `Date.now()` guarantees collision-free DNI and
 * emails across repeated executions (P2002 protection).
 */
export function uniqueTimestamp(): string {
  return Date.now().toString();
}

/**
 * Builds a unique DNI from the run timestamp.
 * Schema constraint: 1..20 chars — a 13-digit timestamp fits.
 */
export function uniqueDni(timestamp: string): string {
  return timestamp;
}

/** Unique guardian email like `tutor1762...@e2e.test`. */
export function uniqueEmail(timestamp: string, prefix = 'tutor'): string {
  return `${prefix}${timestamp}@e2e.test`;
}

// ── Spanish (es-AR) time labels ───────────────────────────────────────────

/**
 * Returns the es-AR 12h label rendered by the TimeSlot select
 * (e.g. `10:00` → "10:00 a. m.", `18:00` → "06:00 p. m.").
 */
export function spanishTimeLabel(hour: number, minute: number): string {
  return new Date(2000, 0, 1, hour, minute).toLocaleTimeString('es-AR', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

// ── Spanish calendar day picker (react-day-picker v10) ────────────────────

/**
 * The day cell `<button aria-label>` is formatted with date-fns locale `es`
 * using the "PPPP" pattern → "miércoles, 19 de agosto de 2026".
 * Returns a regex matching that label regardless of the weekday prefix.
 */
export function dayPickerAriaLabel(date: Date): RegExp {
  const day = format(date, 'd');
  const month = format(date, 'MMMM', { locale: es });
  const year = format(date, 'yyyy');
  return new RegExp(`${day} de ${month}( de)? ${year}`);
}

// ── Golden path scheduling ────────────────────────────────────────────────

export type AppointmentSlot = {
  /** Date to pick in the calendar popover. */
  date: Date;
  /** Time value stored by the select: "10:00" | "18:00". */
  timeValue: string;
  /** es-AR label shown by the select option. */
  timeLabel: string;
  /** True when the slot lands on today (assertable on the dashboard). */
  isToday: boolean;
};

/**
 * Chooses a deterministic, future, non-booked slot:
 *  - before 15:00 → today 18:00 (seed occupies 09:00-11:30 → free, and the
 *    dashboard "Turnos de Hoy" table can be asserted)
 *  - after 15:00  → tomorrow 10:00 (avoids scheduling in the past)
 */
export function futureAppointmentSlot(now: Date = new Date()): AppointmentSlot {
  if (now.getHours() < 15) {
    return {
      date: now,
      timeValue: '18:00',
      timeLabel: spanishTimeLabel(18, 0),
      isToday: true,
    };
  }
  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);
  return {
    date: tomorrow,
    timeValue: '10:00',
    timeLabel: spanishTimeLabel(10, 0),
    isToday: false,
  };
}

/** Seed doctor option label: `fullName — specialty` (see packages/db/prisma/seed.ts). */
export const SEEDED_DOCTOR_OPTION = 'Dr. Ricardo Silva — Pediatra';